import type { VizTrace } from "@/types/visualizer";

const CODE = {
  python: [
    "def search(nums, target):",
    "    left, right = 0, len(nums) - 1",
    "    while left <= right:",
    "        mid = (left + right) // 2",
    "        if nums[mid] == target:",
    "            return mid",
    "        elif nums[mid] < target:",
    "            left = mid + 1",
    "        else:",
    "            right = mid - 1",
    "    return -1",
  ],
  javascript: [
    "function search(nums, target) {",
    "  let left = 0, right = nums.length - 1;",
    "  while (left <= right) {",
    "    const mid = Math.floor((left + right) / 2);",
    "    if (nums[mid] === target) {",
    "      return mid;",
    "    } else if (nums[mid] < target) {",
    "      left = mid + 1;",
    "    } else {",
    "      right = mid - 1;",
    "    }",
    "  }",
    "  return -1;",
    "}",
  ],
  typescript: [
    "function search(nums: number[], target: number): number {",
    "  let left = 0, right = nums.length - 1;",
    "  while (left <= right) {",
    "    const mid = Math.floor((left + right) / 2);",
    "    if (nums[mid] === target) {",
    "      return mid;",
    "    } else if (nums[mid] < target) {",
    "      left = mid + 1;",
    "    } else {",
    "      right = mid - 1;",
    "    }",
    "  }",
    "  return -1;",
    "}",
  ],
  java: [
    "public int search(int[] nums, int target) {",
    "    int left = 0, right = nums.length - 1;",
    "    while (left <= right) {",
    "        int mid = (left + right) / 2;",
    "        if (nums[mid] == target) {",
    "            return mid;",
    "        } else if (nums[mid] < target) {",
    "            left = mid + 1;",
    "        } else {",
    "            right = mid - 1;",
    "        }",
    "    }",
    "    return -1;",
    "}",
  ],
  cpp: [
    "int search(vector<int>& nums, int target) {",
    "    int left = 0, right = nums.size() - 1;",
    "    while (left <= right) {",
    "        int mid = (left + right) / 2;",
    "        if (nums[mid] == target) {",
    "            return mid;",
    "        } else if (nums[mid] < target) {",
    "            left = mid + 1;",
    "        } else {",
    "            right = mid - 1;",
    "        }",
    "    }",
    "    return -1;",
    "}",
  ],
};

const LINES = {
  def:      { python: 1, javascript: 1, typescript: 1, java: 1, cpp: 1 },
  init:     { python: 2, javascript: 2, typescript: 2, java: 2, cpp: 2 },
  whileChk: { python: 3, javascript: 3, typescript: 3, java: 3, cpp: 3 },
  mid:      { python: 4, javascript: 4, typescript: 4, java: 4, cpp: 4 },
  eqCheck:  { python: 5, javascript: 5, typescript: 5, java: 5, cpp: 5 },
  returnMid:{ python: 6, javascript: 6, typescript: 6, java: 6, cpp: 6 },
  moveLeft: { python: 8, javascript: 8, typescript: 8, java: 8, cpp: 8 },
  moveRight:{ python: 10, javascript: 10, typescript: 10, java: 10, cpp: 10 },
};

export const binarySearchTrace: VizTrace = {
  problemSlug: "binary-search",
  code: CODE,
  steps: [
    {
      stepIndex: 0, line: LINES.def, kind: "normal",
      explanation: "We're searching for target=9 in a sorted array. Binary search works only on sorted data.",
      variables: [{ name: "nums", value: "[1,3,5,7,9,11,13]" }, { name: "target", value: 9 }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13] }],
    },
    {
      stepIndex: 1, line: LINES.init, kind: "normal",
      explanation: "We initialize two pointers: left at the start (0), right at the end (6).",
      variables: [{ name: "left", value: 0, changed: true }, { name: "right", value: 6, changed: true }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13], pointers: { left: 0, right: 6 } }],
    },
    {
      stepIndex: 2, line: LINES.whileChk, kind: "compare",
      explanation: "left (0) ≤ right (6), so we continue searching.",
      variables: [{ name: "left", value: 0 }, { name: "right", value: 6 }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13], pointers: { left: 0, right: 6 } }],
    },
    {
      stepIndex: 3, line: LINES.mid, kind: "normal",
      explanation: "mid = (0 + 6) / 2 = 3. We'll check the middle element next.",
      variables: [{ name: "left", value: 0 }, { name: "right", value: 6 }, { name: "mid", value: 3, changed: true }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13], highlight: [3], pointers: { left: 0, right: 6, mid: 3 } }],
    },
    {
      stepIndex: 4, line: LINES.eqCheck, kind: "compare",
      explanation: "nums[3] = 7. Is 7 equal to our target, 9? No — 7 is too small.",
      variables: [{ name: "mid", value: 3 }, { name: "nums[mid]", value: 7 }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13], highlight: [3], pointers: { left: 0, right: 6, mid: 3 } }],
    },
    {
      stepIndex: 5, line: LINES.moveLeft, kind: "normal",
      explanation: "Since 7 < 9, the target must be in the right half. We move left to mid + 1 = 4.",
      variables: [{ name: "left", value: 4, changed: true }, { name: "right", value: 6 }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13], pointers: { left: 4, right: 6 } }],
    },
    {
      stepIndex: 6, line: LINES.mid, kind: "normal",
      explanation: "New mid = (4 + 6) / 2 = 5.",
      variables: [{ name: "left", value: 4 }, { name: "right", value: 6 }, { name: "mid", value: 5, changed: true }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13], highlight: [5], pointers: { left: 4, right: 6, mid: 5 } }],
    },
    {
      stepIndex: 7, line: LINES.eqCheck, kind: "compare",
      explanation: "nums[5] = 11. Is 11 equal to 9? No — 11 is too big this time.",
      variables: [{ name: "mid", value: 5 }, { name: "nums[mid]", value: 11 }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13], highlight: [5], pointers: { left: 4, right: 6, mid: 5 } }],
    },
    {
      stepIndex: 8, line: LINES.moveRight, kind: "normal",
      explanation: "Since 11 > 9, the target must be in the left half. We move right to mid − 1 = 4.",
      variables: [{ name: "left", value: 4 }, { name: "right", value: 4, changed: true }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13], pointers: { left: 4, right: 4 } }],
    },
    {
      stepIndex: 9, line: LINES.mid, kind: "normal",
      explanation: "left equals right now. mid = (4 + 4) / 2 = 4 — our search has narrowed to one element.",
      variables: [{ name: "left", value: 4 }, { name: "right", value: 4 }, { name: "mid", value: 4, changed: true }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13], highlight: [4], pointers: { left: 4, right: 4, mid: 4 } }],
    },
    {
      stepIndex: 10, line: LINES.eqCheck, kind: "success",
      explanation: "nums[4] = 9. That matches our target exactly!",
      variables: [{ name: "mid", value: 4 }, { name: "nums[mid]", value: 9 }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13], success: [4] }],
    },
    {
      stepIndex: 11, line: LINES.returnMid, kind: "success",
      explanation: "We return mid = 4 — the index where 9 lives in the array.",
      variables: [{ name: "result", value: 4, changed: true }],
      array: [{ id: "nums", label: "nums", values: [1,3,5,7,9,11,13], success: [4] }],
    },
  ],
  complexity: {
    time:  "O(log n)",
    space: "O(1)",
    timeExplanation:
      "Each step eliminates half the remaining search space, so the number of steps needed grows logarithmically with input size.",
    spaceExplanation:
      "We only use a constant number of variables (left, right, mid) regardless of input size — no extra data structures.",
  },
};